Date: Sat, 06 Dec 2003 15:41:26 +0000
From: Peter Bloomfield <PeterBloomfield@bellsouth.net>
To: Peter Bloomfield <PeterBloomfield@BellSouth.net>
X-Mailer: Balsa 2.1.0
Message-Id: <1070725286l.24763l.0l@Mercury>
Status: RO
MIME-Version: 1.0
Content-Type: text/plain; charset=ISO-8859-1; DelSp=Yes; Format=Flowed
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Subject: No Subject

