/* eslint-disable quotes */
// Generated!

module.exports = {
  100: 'DC_EVENT_INFO',
  101: 'DC_EVENT_SMTP_CONNECTED',
  102: 'DC_EVENT_IMAP_CONNECTED',
  103: 'DC_EVENT_SMTP_MESSAGE_SENT',
  104: 'DC_EVENT_IMAP_MESSAGE_DELETED',
  105: 'DC_EVENT_IMAP_MESSAGE_MOVED',
  150: 'DC_EVENT_NEW_BLOB_FILE',
  151: 'DC_EVENT_DELETED_BLOB_FILE',
  300: 'DC_EVENT_WARNING',
  400: 'DC_EVENT_ERROR',
  410: 'DC_EVENT_ERROR_SELF_NOT_IN_GROUP',
  2000: 'DC_EVENT_MSGS_CHANGED',
  2005: 'DC_EVENT_INCOMING_MSG',
  2008: 'DC_EVENT_MSGS_NOTICED',
  2010: 'DC_EVENT_MSG_DELIVERED',
  2012: 'DC_EVENT_MSG_FAILED',
  2015: 'DC_EVENT_MSG_READ',
  2020: 'DC_EVENT_CHAT_MODIFIED',
  2021: 'DC_EVENT_CHAT_EPHEMERAL_TIMER_MODIFIED',
  2030: 'DC_EVENT_CONTACTS_CHANGED',
  2035: 'DC_EVENT_LOCATION_CHANGED',
  2041: 'DC_EVENT_CONFIGURE_PROGRESS',
  2051: 'DC_EVENT_IMEX_PROGRESS',
  2052: 'DC_EVENT_IMEX_FILE_WRITTEN',
  2060: 'DC_EVENT_SECUREJOIN_INVITER_PROGRESS',
  2061: 'DC_EVENT_SECUREJOIN_JOINER_PROGRESS',
  2100: 'DC_EVENT_CONNECTIVITY_CHANGED',
  2110: 'DC_EVENT_SELFAVATAR_CHANGED',
  2120: 'DC_EVENT_WEBXDC_STATUS_UPDATE'
}
